INSERT INTO restaurant ( id, is_kosher, name ) VALUES
(1       ,true    ,'Aromatic Restaurant'),
(2       ,true    ,'Tender Restaurant'),
(3       ,false   ,'Tasty Restaurant'),
(4       ,true    ,'Delicious Restaurant'),
(5       ,true    ,'Sizzling Restaurant'),
(6       ,true    ,'Flavorful Restaurant'),
(7       ,true    ,'Tasty Restaurant'),
(8       ,true    ,'Zesty Restaurant'),
(9       ,false   ,'Yummy Restaurant'),
(10      ,false   ,'Tasty Restaurant'),
(11      ,true    ,'Flavorful Restaurant'),
(12      ,true    ,'Tender Restaurant'),
(13      ,false   ,'Zesty Restaurant'),
(14      ,true    ,'Satisfying Restaurant'),
(15      ,true    ,'Mouthwatering Restaurant'),
(16      ,false   ,'Tangy Restaurant'),
(17      ,false   ,'Savory Restaurant'),
(18      ,true    ,'Aromatic Restaurant'),
(19      ,true    ,'Yummy Restaurant'),
(20      ,true    ,'Aromatic Restaurant'),
(21      ,true    ,'Succulent Restaurant'),
(22      ,false   ,'Flavorful Restaurant'),
(23      ,false   ,'Tasty Restaurant'),
(24      ,false   ,'Zesty Restaurant'),
(25      ,true    ,'Tangy Restaurant'),
(26      ,false   ,'Tasty Restaurant'),
(27      ,true    ,'Juicy Restaurant'),
(28      ,true    ,'Delicious Restaurant'),
(29      ,true    ,'Yummy Restaurant'),
(30      ,true    ,'Tangy Restaurant'),
(31      ,true    ,'Sizzling Restaurant'),
(32      ,true    ,'Tender Restaurant'),
(33      ,true    ,'Aromatic Restaurant'),
(34      ,false   ,'Flavorful Restaurant'),
(35      ,false   ,'Succulent Restaurant'),
(36      ,false   ,'Tangy Restaurant'),
(37      ,true    ,'Delicious Restaurant'),
(38      ,true    ,'Tangy Restaurant'),
(39      ,false   ,'Sizzling Restaurant'),
(40      ,false   ,'Sizzling Restaurant'),
(41      ,true    ,'Sizzling Restaurant'),
(42      ,false   ,'Juicy Restaurant'),
(43      ,true    ,'Juicy Restaurant'),
(44      ,false   ,'Sizzling Restaurant'),
(45      ,true    ,'Tender Restaurant'),
(46      ,false   ,'Aromatic Restaurant'),
(47      ,true    ,'Satisfying Restaurant'),
(48      ,true    ,'Hearty Restaurant'),
(49      ,false   ,'Aromatic Restaurant'),
(50      ,true    ,'Hearty Restaurant'),
(51      ,false   ,'Tender Restaurant'),
(52      ,false   ,'Flavorful Restaurant'),
(53      ,true    ,'Succulent Restaurant'),
(54      ,false   ,'Crispy Restaurant'),
(55      ,false   ,'Crispy Restaurant'),
(56      ,true    ,'Succulent Restaurant'),
(57      ,true    ,'Flavorful Restaurant'),
(58      ,true    ,'Aromatic Restaurant'),
(59      ,false   ,'Tasty Restaurant'),
(60      ,true    ,'Tasty Restaurant'),
(61      ,true    ,'Tangy Restaurant'),
(62      ,true    ,'Spicy Restaurant'),
(63      ,false   ,'Spicy Restaurant'),
(64      ,true    ,'Gourmet Restaurant'),
(65      ,true    ,'Sizzling Restaurant'),
(66      ,false   ,'Succulent Restaurant'),
(67      ,false   ,'Mouthwatering Restaurant'),
(68      ,true    ,'Delicious Restaurant'),
(69      ,true    ,'Tangy Restaurant'),
(70      ,false   ,'Tasty Restaurant'),
(71      ,false   ,'Tender Restaurant'),
(72      ,false   ,'Flavorful Restaurant'),
(73      ,false   ,'Tasty Restaurant'),
(74      ,false   ,'Zesty Restaurant'),
(75      ,false   ,'Tender Restaurant'),
(76      ,false   ,'Sizzling Restaurant'),
(77      ,false   ,'Aromatic Restaurant'),
(78      ,true    ,'Succulent Restaurant'),
(79      ,false   ,'Mouthwatering Restaurant'),
(80      ,true    ,'Tasty Restaurant'),
(81      ,true    ,'Yummy Restaurant'),
(82      ,false   ,'Yummy Restaurant'),
(83      ,false   ,'Gourmet Restaurant'),
(84      ,false   ,'Tender Restaurant'),
(85      ,false   ,'Delicious Restaurant'),
(86      ,false   ,'Savory Restaurant'),
(87      ,true    ,'Crispy Restaurant'),
(88      ,false   ,'Tasty Restaurant'),
(89      ,false   ,'Tender Restaurant'),
(90      ,true    ,'Sizzling Restaurant'),
(91      ,true    ,'Satisfying Restaurant'),
(92      ,false   ,'Delicious Restaurant'),
(93      ,true    ,'Flavorful Restaurant'),
(94      ,false   ,'Tasty Restaurant'),
(95      ,false   ,'Hearty Restaurant'),
(96      ,true    ,'Yummy Restaurant'),
(97      ,true    ,'Hearty Restaurant'),
(98      ,false   ,'Juicy Restaurant'),
(99      ,true    ,'Tasty Restaurant'),
(100     ,true    ,'Yummy Restaurant');




INSERT INTO restaurant_cuisines (restaurant_id, cuisines) VALUES
(1,       'Chinese'),
(2,       'Mexican'),
(3,       'Italian'),
(3,       'Chinese'),
(4,       'Chinese'),
(5,       'Mexican'),
(6,       'Chinese'),
(6,       'Indian'),
(6,       'Japanese'),
(7,       'Mexican'),
(7,       'Chinese'),
(7,       'Thai'),
(8,       'Chinese'),
(8,       'Japanese'),
(9,       'Mexican'),
(9,       'Italian'),
(9,       'Japanese'),
(10,      'Thai'),
(10,      'Japanese'),
(11,      'Italian'),
(12,      'Italian'),
(12,      'Indian'),
(12,      'Thai'),
(13,      'Italian'),
(13,      'Chinese'),
(13,      'Japanese'),
(14,      'Japanese'),
(15,      'Indian'),
(16,      'Mexican'),
(16,      'Chinese'),
(16,      'Indian'),
(17,      'Chinese'),
(18,      'Mexican'),
(19,      'Thai'),
(20,      'Indian'),
(21,      'Indian'),
(22,      'Italian'),
(23,      'Mexican'),
(23,      'Thai'),
(24,      'Indian'),
(25,      'Thai'),
(26,      'Chinese'),
(26,      'Thai'),
(26,      'Japanese'),
(27,      'Mexican'),
(27,      'Indian'),
(27,      'Thai'),
(28,      'Japanese'),
(29,      'Italian'),
(30,      'Mexican'),
(30,      'Thai'),
(31,      'Italian'),
(31,      'Chinese'),
(31,      'Thai'),
(32,      'Thai'),
(32,      'Japanese'),
(33,      'Japanese'),
(34,      'Indian'),
(34,      'Thai'),
(35,      'Italian'),
(36,      'Chinese'),
(37,      'Indian'),
(37,      'Thai'),
(38,      'Japanese'),
(39,      'Mexican'),
(39,      'Italian'),
(39,      'Chinese'),
(40,      'Italian'),
(40,      'Mexican'),
(41,      'Mexican'),
(42,      'Chinese'),
(42,      'Thai'),
(43,      'Italian'),
(44,      'Japanese'),
(45,      'Italian'),
(45,      'Chinese'),
(45,      'Japanese'),
(46,      'Indian'),
(47,      'Mexican'),
(48,      'Mexican'),
(49,      'Indian'),
(50,      'Japanese'),
(51,      'Italian'),
(51,      'Japanese'),
(52,      'Italian'),
(52,      'Thai'),
(52,      'Japanese'),
(53,      'Thai'),
(53,      'Japanese'),
(54,      'Mexican'),
(54,      'Chinese'),
(54,      'Thai'),
(55,      'Mexican'),
(55,      'Thai'),
(56,      'Thai'),
(57,      'Thai'),
(58,      'Indian'),
(58,      'Japanese'),
(59,      'Mexican'),
(59,      'Chinese'),
(60,      'Chinese'),
(61,      'Japanese'),
(62,      'Indian'),
(62,      'Thai'),
(63,      'Chinese'),
(64,      'Mexican'),
(64,      'Japanese'),
(65,      'Indian'),
(65,      'Japanese'),
(66,      'Chinese'),
(67,      'Thai'),
(67,      'Japanese'),
(68,      'Indian'),
(69,      'Chinese'),
(70,      'Italian'),
(70,      'Thai'),
(70,      'Japanese'),
(71,      'Italian'),
(71,      'Japanese'),
(72,      'Mexican'),
(72,      'Indian'),
(73,      'Mexican'),
(73,      'Indian'),
(74,      'Italian'),
(74,      'Chinese'),
(74,      'Thai'),
(75,      'Indian'),
(75,      'Chinese'),
(76,      'Indian'),
(76,      'Japanese'),
(77,      'Italian'),
(78,      'Indian'),
(79,      'Japanese'),
(80,      'Japanese'),
(81,      'Italian'),
(81,      'Thai'),
(81,      'Japanese'),
(82,      'Mexican'),
(82,      'Japanese'),
(83,      'Italian'),
(83,      'Thai'),
(84,      'Indian'),
(85,      'Mexican'),
(85,      'Chinese'),
(86,      'Italian'),
(86,      'Mexican'),
(86,      'Chinese'),
(87,      'Mexican'),
(87,      'Indian'),
(87,      'Thai'),
(88,      'Mexican'),
(88,      'Chinese'),
(89,      'Italian'),
(89,      'Indian'),
(90,      'Italian'),
(91,      'Chinese'),
(91,      'Japanese'),
(92,      'Italian'),
(93,      'Italian'),
(94,      'Japanese'),
(95,      'Mexican'),
(96,      'Indian'),
(96,      'Chinese'),
(97,      'Japanese'),
(98,      'Italian'),
(98,      'Chinese'),
(99,      'Indian'),
(99,      'Chinese'),
(100,     'Italian');