CREATE TABLE IF NOT EXISTS restaurant (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    is_kosher boolean,
    name character varying(60)
);

CREATE TABLE IF NOT EXISTS dish (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    description VARCHAR(300),
    name VARCHAR(60),
    price real,
    restaurant_id INT
);

CREATE TABLE IF NOT EXISTS restaurant_order (
    id uuid NOT NULL PRIMARY KEY,
    restaurant_id INT
);

CREATE TABLE IF NOT EXISTS order_item (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    amount INT,
    dish_id INT,
    order_id uuid
);

CREATE TABLE IF NOT EXISTS restaurant_cuisines (
    restaurant_id INT NOT NULL,
    cuisines VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS restaurant_rating (
    id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    rating REAL,
    restaurant_id INT
);

INSERT INTO restaurant ( is_kosher, name ) VALUES
(true    ,'Aromatic Restaurant'),
(true    ,'Tender Restaurant'),
(false   ,'Tasty Restaurant'),
(true    ,'Delicious Restaurant'),
(true    ,'Sizzling Restaurant'),
(true    ,'Flavorful Restaurant'),
(true    ,'Tasty Restaurant'),
(true    ,'Zesty Restaurant'),
(false   ,'Yummy Restaurant'),
(false   ,'Tasty Restaurant'),
(true    ,'Flavorful Restaurant'),
(true    ,'Tender Restaurant'),
(false   ,'Zesty Restaurant'),
(true    ,'Satisfying Restaurant'),
(true    ,'Mouthwatering Restaurant'),
(false   ,'Tangy Restaurant'),
(false   ,'Savory Restaurant'),
(true    ,'Aromatic Restaurant'),
(true    ,'Yummy Restaurant'),
(true    ,'Aromatic Restaurant'),
(true    ,'Succulent Restaurant'),
(false   ,'Flavorful Restaurant'),
(false   ,'Tasty Restaurant'),
(false   ,'Zesty Restaurant'),
(true    ,'Tangy Restaurant'),
(false   ,'Tasty Restaurant'),
(true    ,'Juicy Restaurant'),
(true    ,'Delicious Restaurant'),
(true    ,'Yummy Restaurant'),
(true    ,'Tangy Restaurant'),
(true    ,'Sizzling Restaurant'),
(true    ,'Tender Restaurant'),
(true    ,'Aromatic Restaurant'),
(false   ,'Flavorful Restaurant'),
(false   ,'Succulent Restaurant'),
(false   ,'Tangy Restaurant'),
(true    ,'Delicious Restaurant'),
(true    ,'Tangy Restaurant'),
(false   ,'Sizzling Restaurant'),
(false   ,'Sizzling Restaurant'),
(true    ,'Sizzling Restaurant'),
(false   ,'Juicy Restaurant'),
(true    ,'Juicy Restaurant'),
(false   ,'Sizzling Restaurant'),
(true    ,'Tender Restaurant'),
(false   ,'Aromatic Restaurant'),
(true    ,'Satisfying Restaurant'),
(true    ,'Hearty Restaurant'),
(false   ,'Aromatic Restaurant'),
(true    ,'Hearty Restaurant'),
(false   ,'Tender Restaurant'),
(false   ,'Flavorful Restaurant'),
(true    ,'Succulent Restaurant'),
(false   ,'Crispy Restaurant'),
(false   ,'Crispy Restaurant'),
(true    ,'Succulent Restaurant'),
(true    ,'Flavorful Restaurant'),
(true    ,'Aromatic Restaurant'),
(false   ,'Tasty Restaurant'),
(true    ,'Tasty Restaurant'),
(true    ,'Tangy Restaurant'),
(true    ,'Spicy Restaurant'),
(false   ,'Spicy Restaurant'),
(true    ,'Gourmet Restaurant'),
(true    ,'Sizzling Restaurant'),
(false   ,'Succulent Restaurant'),
(false   ,'Mouthwatering Restaurant'),
(true    ,'Delicious Restaurant'),
(true    ,'Tangy Restaurant'),
(false   ,'Tasty Restaurant'),
(false   ,'Tender Restaurant'),
(false   ,'Flavorful Restaurant'),
(false   ,'Tasty Restaurant'),
(false   ,'Zesty Restaurant'),
(false   ,'Tender Restaurant'),
(false   ,'Sizzling Restaurant'),
(false   ,'Aromatic Restaurant'),
(true    ,'Succulent Restaurant'),
(false   ,'Mouthwatering Restaurant'),
(true    ,'Tasty Restaurant'),
(true    ,'Yummy Restaurant'),
(false   ,'Yummy Restaurant'),
(false   ,'Gourmet Restaurant'),
(false   ,'Tender Restaurant'),
(false   ,'Delicious Restaurant'),
(false   ,'Savory Restaurant'),
(true    ,'Crispy Restaurant'),
(false   ,'Tasty Restaurant'),
(false   ,'Tender Restaurant'),
(true    ,'Sizzling Restaurant'),
(true    ,'Satisfying Restaurant'),
(false   ,'Delicious Restaurant'),
(true    ,'Flavorful Restaurant'),
(false   ,'Tasty Restaurant'),
(false   ,'Hearty Restaurant'),
(true    ,'Yummy Restaurant'),
(true    ,'Hearty Restaurant'),
(false   ,'Juicy Restaurant'),
(true    ,'Tasty Restaurant'),
(true    ,'Yummy Restaurant');




INSERT INTO restaurant_cuisines (restaurant_id, cuisines) VALUES
(1,       'Chinese'),
(2,       'Mexican'),
(3,       'Italian'),
(3,       'Chinese'),
(4,       'Chinese'),
(5,       'Mexican'),
(6,       'Chinese'),
(6,       'Indian'),
(6,       'Japanese'),
(7,       'Mexican'),
(7,       'Chinese'),
(7,       'Thai'),
(8,       'Chinese'),
(8,       'Japanese'),
(9,       'Mexican'),
(9,       'Italian'),
(9,       'Japanese'),
(10,      'Thai'),
(10,      'Japanese'),
(11,      'Italian'),
(12,      'Italian'),
(12,      'Indian'),
(12,      'Thai'),
(13,      'Italian'),
(13,      'Chinese'),
(13,      'Japanese'),
(14,      'Japanese'),
(15,      'Indian'),
(16,      'Mexican'),
(16,      'Chinese'),
(16,      'Indian'),
(17,      'Chinese'),
(18,      'Mexican'),
(19,      'Thai'),
(20,      'Indian'),
(21,      'Indian'),
(22,      'Italian'),
(23,      'Mexican'),
(23,      'Thai'),
(24,      'Indian'),
(25,      'Thai'),
(26,      'Chinese'),
(26,      'Thai'),
(26,      'Japanese'),
(27,      'Mexican'),
(27,      'Indian'),
(27,      'Thai'),
(28,      'Japanese'),
(29,      'Italian'),
(30,      'Mexican'),
(30,      'Thai'),
(31,      'Italian'),
(31,      'Chinese'),
(31,      'Thai'),
(32,      'Thai'),
(32,      'Japanese'),
(33,      'Japanese'),
(34,      'Indian'),
(34,      'Thai'),
(35,      'Italian'),
(36,      'Chinese'),
(37,      'Indian'),
(37,      'Thai'),
(38,      'Japanese'),
(39,      'Mexican'),
(39,      'Italian'),
(39,      'Chinese'),
(40,      'Italian'),
(40,      'Mexican'),
(41,      'Mexican'),
(42,      'Chinese'),
(42,      'Thai'),
(43,      'Italian'),
(44,      'Japanese'),
(45,      'Italian'),
(45,      'Chinese'),
(45,      'Japanese'),
(46,      'Indian'),
(47,      'Mexican'),
(48,      'Mexican'),
(49,      'Indian'),
(50,      'Japanese'),
(51,      'Italian'),
(51,      'Japanese'),
(52,      'Italian'),
(52,      'Thai'),
(52,      'Japanese'),
(53,      'Thai'),
(53,      'Japanese'),
(54,      'Mexican'),
(54,      'Chinese'),
(54,      'Thai'),
(55,      'Mexican'),
(55,      'Thai'),
(56,      'Thai'),
(57,      'Thai'),
(58,      'Indian'),
(58,      'Japanese'),
(59,      'Mexican'),
(59,      'Chinese'),
(60,      'Chinese'),
(61,      'Japanese'),
(62,      'Indian'),
(62,      'Thai'),
(63,      'Chinese'),
(64,      'Mexican'),
(64,      'Japanese'),
(65,      'Indian'),
(65,      'Japanese'),
(66,      'Chinese'),
(67,      'Thai'),
(67,      'Japanese'),
(68,      'Indian'),
(69,      'Chinese'),
(70,      'Italian'),
(70,      'Thai'),
(70,      'Japanese'),
(71,      'Italian'),
(71,      'Japanese'),
(72,      'Mexican'),
(72,      'Indian'),
(73,      'Mexican'),
(73,      'Indian'),
(74,      'Italian'),
(74,      'Chinese'),
(74,      'Thai'),
(75,      'Indian'),
(75,      'Chinese'),
(76,      'Indian'),
(76,      'Japanese'),
(77,      'Italian'),
(78,      'Indian'),
(79,      'Japanese'),
(80,      'Japanese'),
(81,      'Italian'),
(81,      'Thai'),
(81,      'Japanese'),
(82,      'Mexican'),
(82,      'Japanese'),
(83,      'Italian'),
(83,      'Thai'),
(84,      'Indian'),
(85,      'Mexican'),
(85,      'Chinese'),
(86,      'Italian'),
(86,      'Mexican'),
(86,      'Chinese'),
(87,      'Mexican'),
(87,      'Indian'),
(87,      'Thai'),
(88,      'Mexican'),
(88,      'Chinese'),
(89,      'Italian'),
(89,      'Indian'),
(90,      'Italian'),
(91,      'Chinese'),
(91,      'Japanese'),
(92,      'Italian'),
(93,      'Italian'),
(94,      'Japanese'),
(95,      'Mexican'),
(96,      'Indian'),
(96,      'Chinese'),
(97,      'Japanese'),
(98,      'Italian'),
(98,      'Chinese'),
(99,      'Indian'),
(99,      'Chinese'),
(100,     'Italian');
